/* Generated by Yosys 0.32+66 (git sha1 2f901a829, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module mult8(a, y);
  input [2:0] a;
  wire [2:0] a;
  output [5:0] y;
  wire [5:0] y;
  assign y = { a, a };
endmodule
